# java environment variables
alias set-java-7='export JAVA_HOME=/home/anderson/sisbride/sdk/jdk1.7.0_45;export JRE_HOME=/home/anderson/sisbride/sdk/jdk1.7.0_45;export PATH=$JAVA_HOME/bin:$PATH;'
alias set-java-6='export JAVA_HOME=/home/anderson/sisbride/sdk/jdk1.6.0_45;export JRE_HOME=/home/anderson/sisbride/sdk/jdk1.6.0_45;export PATH=$JAVA_HOME/bin:$PATH;'
alias set-java-5='export JAVA_HOME=/home/anderson/sisbride/sdk/jdk1.5.0_22;export JRE_HOME=/home/anderson/sisbride/sdk/jdk1.5.0_22;export PATH=$JAVA_HOME/bin:$PATH;'

# maven commands
alias ec='mvn eclipse:clean eclipse:eclipse -Dversao.source.java=1.7 -Dversao.target.java=1.7'
alias io='mvn clean compile install -DskipTests'

# shell basic commands
alias l='ls'
alias ll='ls -l'
alias la='ls -la'
alias cd..='cd ..'
alias mkdir='mkdir -p'

export LESS="-R"
eval "$(lesspipe)"
